feat: Node.js Dev Doc(Official)
ZeroOctave/resource-gallery pull request #256
Opened 2023-07-24 05:00 UTC by NarendraKoya999

## Related Issue

Closes: #251 

## Description of Changes
- **Updated `Node.js Dev Doc (Official) in  frameworks.astro File` for Learning Node.js PRO Level**
## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| ![Original screenshot](link) | ![Updated screenshot](link) |

Please provide any necessary screenshots to illustrate the changes made.

2023-07-24 05:03 UTC, NarendraKoya999 commented
@bhartik021 . Please Review on My PR

2023-07-30 12:07 UTC, Alkaison approved these changes
All good!

2023-07-30 12:09 UTC, Alkaison requested changes

2023-07-30 12:09 UTC, Alkaison commented on src/pages/frameworks.astro
It has merge conflicts and also I noticed that the resource has been added under a recent PR, try adding some new resource for Node.js.

2023-07-30 12:36 UTC, NarendraKoya999 commented on src/pages/frameworks.astro
@Alkaison . It's Different Thing. This Resource is helpful for Continue Learning of JavaScript along with Node.js from Very Basic Level to Advanced Level.

2023-07-31 14:40 UTC, merged