blog added
ZeroOctave/resource-gallery pull request #261
Opened 2023-07-24 18:09 UTC by anshulsoni4

## Related Issue
added one more blog 

Closes: #229

## Description of Changes
added new blog

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

![image](https://github.com/ZeroOctave/resource-gallery/assets/74638335/2341c95b-af9a-4717-a125-d727eaac90e5)

Please provide any necessary screenshots to illustrate the changes made.

2023-07-30 11:59 UTC, anshulsoni4 commented
pls reviewwwww .....

2023-07-30 12:05 UTC, Alkaison requested changes

2023-07-30 12:05 UTC, Alkaison commented on src/pages/blog/Understanding Cloud Technology: A Comprehensive Guide.md
Branch has conflicts and I can't see your new blog file.

2023-07-30 12:11 UTC, anshulsoni4 reviewed
pls check now

2023-07-30 12:12 UTC, Alkaison commented
Push your changes and also resolve the conflict

2023-08-01 05:56 UTC, anshulsoni4 commented
never mind, i will create a new one

2023-08-01 06:07 UTC, anshulsoni4 commented
> Push your changes and also resolve the conflict

![image](https://github.com/ZeroOctave/resource-gallery/assets/74638335/42d2ffb1-d39f-4cc9-9df4-905f2d4c4cce)


the changes are visible in the code, i dont understand where are the conflicts

2023-08-01 06:29 UTC, Alkaison commented
This file `src/pages/blog/Understanding Cloud Technology: A Comprehensive Guide.md` has conflicts.

2023-08-01 07:07 UTC, anshulsoni4 reviewed
pls review now, also add the gssoc tag

2023-08-02 06:43 UTC, anshulsoni4 commented
hey @Alkaison pls review

2023-08-02 16:58 UTC, Alkaison commented
- There are no changes to be considered in this PR, check this...

![image](https://github.com/ZeroOctave/resource-gallery/assets/98116504/ec769513-4558-49cb-a23b-86a02faa4f36)

2023-08-02 16:58 UTC, closed without merging